<?php

namespace ContainerD8jVxkl;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActualiteRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ActualiteRepository' shared autowired service.
     *
     * @return \App\Repository\ActualiteRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ActualiteRepository'] = new \App\Repository\ActualiteRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
