<?php

namespace ContainerD8jVxkl;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCoursControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\CoursController' shared autowired service.
     *
     * @return \App\Controller\CoursController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\CoursController'] = $instance = new \App\Controller\CoursController();

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('App\\Controller\\CoursController', $container));

        return $instance;
    }
}
