<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD8jVxkl\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD8jVxkl/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerD8jVxkl.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerD8jVxkl\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerD8jVxkl\App_KernelProdContainer([
    'container.build_hash' => 'D8jVxkl',
    'container.build_id' => '1dbf2a3f',
    'container.build_time' => 1684767208,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD8jVxkl');
