<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHt6uFEj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHt6uFEj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHt6uFEj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHt6uFEj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHt6uFEj\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ht6uFEj',
    'container.build_id' => 'cf0387de',
    'container.build_time' => 1683205231,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHt6uFEj');
