<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYqNFfxC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYqNFfxC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYqNFfxC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYqNFfxC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYqNFfxC\App_KernelDevDebugContainer([
    'container.build_hash' => 'YqNFfxC',
    'container.build_id' => '5074107f',
    'container.build_time' => 1684915766,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYqNFfxC');
